routes/web.php
<?php

// SPDX-FileCopyrightText: 2021 Marten Koetsier <eicas@koetsierengineering.nl>
//
// SPDX-License-Identifier: MIT

use App\Http\Controllers\GuestController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/dashboard', [UserController::class, 'index'])->name('user.home')->middleware('user');
require_once(__DIR__ . "/web.profile.php");
require_once(__DIR__ . "/web.cms.php");
require_once(__DIR__ . "/web.guest_forms.php");

Route::get('downloads/{filename}', [GuestController::class, 'download'])->name('download');

Route::get('/{slug?}', [GuestController::class, 'show'])->where('slug', '.*');

app/Models/User.php
<?php

// SPDX-FileCopyrightText: 2021 - 2022 Marten Koetsier <eicas@koetsierengineering.nl>
//
// SPDX-License-Identifier: MIT

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Illuminate\Contracts\Auth\MustVerifyEmail as MustVerifyEmailContract;
use Illuminate\Auth\Authenticatable;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Traits\Profile\CanResetPassword;
use App\Traits\Profile\MfaAuthenticatable;
use App\Traits\Profile\MustVerifyEmail;
use App\Models\UserSession;
use App\Models\Role;

class User extends Model implements
	AuthorizableContract,
	AuthenticatableContract,
	CanResetPasswordContract,
	MustVerifyEmailContract {

	use
		Authenticatable, Authorizable, CanResetPassword, MustVerifyEmail,
		Notifiable, SoftDeletes, MfaAuthenticatable;

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = [
		'name',
		'email',
		'password',
	];

	/**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	protected $hidden = [
		'password',
		'mfa_secret',
		'mfa_recovery_codes',
		// 'remember_token',
	];

	/**
	 * The attributes that should be cast to native types.
	 *
	 * @var array
	 */
	protected $casts = [
		'id' => 'integer',
		'email_verified_at' => 'datetime',
		'mfa_confirmed_at' => 'datetime',
		'created_at' => 'datetime',
		'updated_at' => 'datetime',
		'deleted_at' => 'datetime',
	];

	protected $userSession = null;

	public function roles() {
		return $this->belongsToMany(Role::class);
	}

	public function userSessions() {
		return $this->hasMany(UserSession::class)->orderBy('updated_at', 'desc');
	}

	public function setUserSessionAttribute(UserSession $userSession) {
		$this->userSession = $userSession;
	}

	public function getUserSessionAttribute() {
		return $this->userSession;
	}

	public function loadUserSession() {
		$session_id = session()->getId();
		foreach ($this->userSessions as $userSession) {
			if ($userSession->session_id === $session_id) {
				$this->userSession = $userSession;
				break;
			}
		}
	}

	/**
	 * Get the token value for the "remember me" session.
	 * 
	 * This method is overridden from Illuminate\Auth\Authenticatable.
	 * 
	 * A User model does not have a remember token. Instead, it has multiple sessions (UserSession model) associated
	 * which in turn can have a remember token. Therefore, getting the token depends on the actual session.
	 * 
	 * This method returns the remember token for the current session, if one is available, or null otherwise.
	 *
	 * @return string|null
	 */
	public function getRememberToken() {
		// logger("[User::getRememberToken] return token '" . optional($this->userSession)->remember_token . "'.");
		return optional($this->userSession)->remember_token;
	}

	/**
	 * Set the token value for the "remember me" session.
	 *
	 * This method is overridden from Illuminate\Auth\Authenticatable.
	 * 
	 * A User model does not have a remember token. Instead, it has multiple sessions (UserSession model) associated
	 * which in turn can have a remember token. Therefore, setting the token depends on the actual session.
	 * 
	 * This method sets the remember token on the current session, if one is available.
	 *
	 * @param  string  $value
	 * @return void
	 */
	public function setRememberToken($value) {
		// logger("[User] setRememberToken('$value')");
		if ($this->userSession) {
			// logger("[User] current userSession: id={$this->userSession->id}; set the token");
			$this->userSession->setRememberToken($value); // will also save
		}
	}

	/**
	 * Determine whether the user has a specific role.
	 *
	 * To determine whether the user is allowed to do administrative tasks on a specific subject, use the admin-method
	 * on the policy: User::can('admin', <the class>), as this also takes into account whether the user has the 'admin'
	 * role (except for the user policy, which is slightly more complicated).
	 *
	 * @param \App\Models\Role|string $role
	 * @return boolean
	 */
	public function hasRole($role): bool {
		$role = $role->key ?? $role;
		foreach ($this->roles as $user_role) {
			if ($user_role->key === $role) {
				return true;
			}
		}
		return false;
	}

	/**
	 * Determine whether the user has at least one of the specified roles.
	 *
	 * To determine whether the user is allowed to do administrative tasks on a specific subject, use the admin-method
	 * on the policy: User::can('admin', <the class>), as this also takes into account whether the user has the 'admin'
	 * role (except for the user policy, which is slightly more complicated).
	 *
	 * @param \App\Models\Role[]|string[] $roles
	 * @return boolean
	 */
	public function hasAnyRole(array $roles): bool {
		foreach ($roles as &$role) {
			$role = $role->key ?? $role;
		}
		foreach ($this->roles as $user_role) {
			if (in_array($user_role->key, $roles)) {
				return true;
			}
		}
		return false;
	}

	/**
	 * Return a list of id's of users with at least one admin-like role, i.e. the EICAS users.
	 *
	 * @return integer[]
	 */
	public static function getAdminUserIds(): array {
		return
			// get all users which have at least one 'admin' like role
			// list their id's and return the id's as an array
			User::whereHas('roles', function ($q) {
				$q->where('key','like','%admin%');
			})->get()->pluck('id')->all();
	}
}

app/Http/Controllers/Profile/UserController.php
<?php

// SPDX-FileCopyrightText: 2021 Marten Koetsier <eicas@koetsierengineering.nl>
//
// SPDX-License-Identifier: MIT

namespace App\Http\Controllers\Profile;

use App\Http\Controllers\Controller;
use App\Http\Requests\Profile\UpdateUserRequest;
use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;

/**
 * This UserController handles actions around user management. I.e. creating/updating/deleting users.
 */
class UserController extends Controller {
	public function __construct() {
		$this->authorizeResource(User::class, 'user');
	}

	/**
	 * Display a listing of the resource.
	 * 
	 * The request may include an extra GET parameter: 'admin' with possible values 0 or 1.
	 * 0: manage only non-EICAS users, i.e. friends and subscribers.
	 * 1: manage only EICAS users, i.e. admin, user-admin, text-admin, art-admin, and menu-admin.
	 * This setting is stored in the users session (key: 'user-admin.admin') and only reset if a new value is set here.
	 * Default value: 1 (show EICAS users only)
	 *
	 * @param \Illuminate\Http\Request $request
	 * @return \Illuminate\Http\Response
	 */
	public function index(Request $request) {
		// get the id's of the users with at least one admin-like role, i.e. the EICAS users:
		// // note: resulting records are not Roles
		// $admin_user_ids = Role::join('role_user','role_user.role_id','=','roles.id')
		// 	// find only admin-like roles
		// 	->where('roles.key','like','%admin%')
		// 	// get the user id's via the joined role_user table
		// 	->select('role_user.user_id')
		// 	// group to prevent duplicate users
		// 	->groupBy('role_user.user_id')
		// 	// put the id's into an array
		// 	->get()->pluck('user_id')->all();
		// // use the id-list to pre-select the users
		$admin_user_ids = User::getAdminUserIds();

		// determine whether EICAS-users or non-EICAS users are requested
		$admin = $request->session()->get('user-admin.admin', 1) ? 1 : 0;
		if ($request->has('admin')) {
			$admin = $request->admin ? 1 : 0;
			$request->session()->put('user-admin.admin', $admin);
		}
		if ($admin) {
			$users = User::whereIn('id', $admin_user_ids);
		} else {
			$users = User::whereNotIn('id', $admin_user_ids);
		}
		$users = $users->with('roles')->withCount('userSessions')->get();
		return view('users.index', ['users' => $users]);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		//
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param \Illuminate\Http\Request $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request) {
		//
	}

	/**
	 * Display the specified resource.
	 * 
	 * This route makes use of the edit blade, with a special variable 'show' set to true to disable forms.
	 *
	 * @param \App\Models\User $user
	 * @return \Illuminate\Http\Response
	 */
	public function show(User $user) {
		$user->load(['userSessions', 'roles']);
		$roles = Role::get();
		return view('users.edit', ['show' => true, 'user' => $user, 'roles' => $roles]);
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param \App\Models\User $user
	 * @return \Illuminate\Http\Response
	 */
	public function edit(User $user) {
		$user->load(['userSessions', 'roles']);
		$roles = Role::get();
		return view('users.edit', ['user' => $user, 'roles' => $roles]);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param \App\Http\Requests\Profile\UpdateUserRequest $request
	 * @param \App\Models\User $user
	 * @return \Illuminate\Http\Response
	 */
	public function update(UpdateUserRequest $request, User $user) {
		$user->fill($request->safe()->only(['name', 'email']));
		$user->save();
		$user->roles()->sync(
			Role::whereIn(
				'key',
				$request->safe()->only(['roles'])['roles'] // keys of selected roles
			)->get()->pluck('id')->all() // get id's of those selected roles
		);
		return redirect()->route('profiles.edit', ['user' => $user]);
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param \App\Models\User $user
	 * @return \Illuminate\Http\Response
	 */
	public function destroy(User $user) {
		$user->delete();
		return redirect()->route('profiles.index');
	}
}

app/Http/Controllers/UserController.php
<?php

// SPDX-FileCopyrightText: 2021 Marten Koetsier <eicas@koetsierengineering.nl>
//
// SPDX-License-Identifier: MIT

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

/**
 * This UserController handles actions for regular users which do not belong to a certain group of actions.
 * I.e. "other" actions.
 */
class UserController extends Controller {
	/**
	 * Show the user dashboard view (user.index).
	 * 
	 * The blade file checks the current user's roles to determine what links to show.
	 *
	 * @param \Illuminate\Http\Request $request
	 * @return \Illuminate\Http\Response
	 */
	public function index(Request $request) {
		$parameters = [
			'internal_users_count' => 0,
			'external_users_count' => 0,
		];
		if ($request->user()->hasAnyRole(['admin', 'user-admin'])) {
			$parameters['internal_users_count'] = count(User::getAdminUserIds());
			$parameters['external_users_count'] = User::count() - $parameters['internal_users_count'];
		}

		return view('user.index', $parameters);
	}
}

resources/views/users/edit.blade.php
{{--
SPDX-FileCopyrightText: 2021 Marten Koetsier <eicas@koetsierengineering.nl>
SPDX-FileCopyrightText: 2022 Arnout Engelen <arnout@bzzt.net>

SPDX-License-Identifier: MIT
--}}

@extends('layouts.user')

@php
	// This view is used both for the show action and the edit action. If the show action was called,
	// the variable $show will be set to true.
	// Here, make sure that the variable exists and default it to false if not.
	$show = isset($show) ? $show : false;
@endphp
@section('main')
<h2>Details gebruiker {{ $user->name }}</h2>

@if ($show && $user->id === Auth::id())
<div class="alert"><p>U kunt uw eigen gebruikersprofiel niet aanpassen.</p></div>
@elseif ($show)
<div class="alert"><p>U kunt het profiel van deze gebruiker niet aanpassen.</p></div>
@endif

<form id="update" method="POST" action="{{ $show ? '' : route('profiles.update', ['user' => $user]) }}"{!!
	$show ? ' disabled="disabled"' : ''
!!}>
	@csrf
	@method('PATCH')

	<label for="name">Naam</label>
	<input type="text" id="name" name="name" value="{{ old('name', $user->name) }}" required{!!
		$show ? ' readonly="true"' : ''
	!!}>

	<label for="email">E-mail (login)</label>
	<input type="email" id="email" name="email" value="{{ old('email', $user->email) }}" required{!!
		$show ? ' readonly="true"' : ''
	!!}>

	<label>Rollen</label>
	<div class="multiple multiple-auto-rest">
		@foreach ($roles as $role)
		<label>
			<input type="checkbox" name="roles[]" value="{{ $role->key }}"{!!
				$user->hasRole($role->key) ? ' checked' : ''
			!!}{!! $show ? ' disabled' : '' !!}>
			{{ $role->translatedName }}
		</label>
		<span>{{ $role->translatedDescription }}</span>
		@endforeach
	</div>

	@unless($show)
	<button type="submit">🖫 Opslaan</button>
	@endunless
</form>

<h3>Data</h3>
<table>
	<thead>
		<tr>
			<th>Aangemeld</th>
			<th>E-mail geverifieerd</th>
			<th>Laatst gewijzigd</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>{{ $user->created_at }}</td>
			<td>{{ $user->email_verified_at }}</td>
			<td>{{ $user->updated_at }}</td>
		</tr>
	</tbody>
</table>

<h3>Inlogsessies</h3>
<table>
	<thead>
		<tr>
			<th>Start</th>
			<th>Duur</th>
			<th>Activiteit</th>
			<th>ip-adres</th>
			<th>Browser</th>
			<th>Status</th>
			<th>Permanent</th>
			<th>Acties</th>
		</tr>
	</thead>
	<tbody>
		@foreach ($user->userSessions as $userSession)
		<tr{!! $userSession->id === ($user->userSession->id ?? 0) ? ' style="font-style:italic"' : '' !!}>
			<td>{{ $userSession->created_at }}</td>
			<td>{{ \App\Helpers\Misc::timeFromSeconds($userSession->updated_at->diffInSeconds($userSession->created_at)) }}</td>
			<td>{{ $userSession->number_of_visits }}</td>
			<td>{{ $userSession->ip }}</td>
			<td title="{{ $userSession->user_agent }}">{{ \App\Helpers\Misc::shortUserAgent($userSession->user_agent) }}</td>
			<td>{{ $userSession->expired ? "verlopen (" . \App\Helpers\Misc::timeFromSeconds($userSession->expired) . ")" : 'actief' }}</td>
			<td>{{ $userSession->canRemember ? 'ja' : 'nee' }}</td>
			<td>
				@if ($userSession->id === ($user->userSession->id ?? 0))
				huidige sessie
				@elseif ($userSession->canRemember && !$userSession->expired && (!$show || $user->id === Auth::id()))
				<form class="no-layout" id="form-user-session-{{ $userSession->id }}" method="POST" action="{{
					route('profile.session.delete', ['user' => $user, 'userSession' => $userSession])
				}}">
					@csrf
					@method('DELETE')
					<button type="submit">uitloggen</button>
				</form>
				@endif
			</td>
		</tr>
		@endforeach
	</tbody>
</table>

<h3>Account verwijderen</h3>
<form id="delete" method="POST" action="{{ route('profiles.destroy', ['user' => $user])
}}" onsubmit="return confirm('Zeker weten?')" class="no-layout">
	@csrf
	@method('DELETE')
	<button type="submit">Account verwijderen</button>
</form>
@endsection

resources/views/users/index.blade.php
{{--
SPDX-FileCopyrightText: 2021 Marten Koetsier <eicas@koetsierengineering.nl>

SPDX-License-Identifier: MIT
--}}

@extends('layouts.user')

@section('main')
<h2>Gebruikersbeheer</h2>
<table>
	<thead>
		<tr>
			<th>Naam</th>
			<th>Email (loginnaam)</th>
			{{-- <th>MFA</th> --}}
			<th>Aangemeld</th>
			<th>Gewijzigd</th>
			<th>Rollen</th>
			<th title="aantal Actieve Sessies">#AS*</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach ($users as $user)
		<tr>
			<td>{{ $user->name }}</td>
			<td style="{!!
				is_null($user->email_verified_at) ? 'font-style:italic' : 'font-weight:bold'
			!!}">{{ $user->email }}</td>
			{{-- <td>{{ is_null($user->mfa_confirmed_at) ? 'nee' : 'ja' }}</td> --}}
			<td style="white-space:nowrap">{{ $user->created_at->format('Y-m-d H:i') }}</td>
			<td style="white-space:nowrap">{{ $user->updated_at->format('Y-m-d H:i') }}</td>
			<td>
				<ul class="roles">
					@foreach ($user->roles as $role)
					<li>{{ $role->translatedName }}</li>
					@endforeach
				</ul>
			</td>
			<td>{{ $user->user_sessions_count }}</td>
			<td>
				<form class="no-layout" method="GET" action="{{
					route('profiles.' . (Auth::user()->can('update', $user) ? 'edit' : 'show'), ['user' => $user])
				}}">
					<button type="submit">details</button>
				</form>
			</td>
		</tr>
		@endforeach
	</tbody>
</table>
<p>
	* #AS = aantal Actieve Sessies.
</p>
@endsection