routes/web.php
<?php

// SPDX-FileCopyrightText: 2021 Marten Koetsier <eicas@koetsierengineering.nl>
//
// SPDX-License-Identifier: MIT

use App\Http\Controllers\GuestController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/dashboard', [UserController::class, 'index'])->name('user.home')->middleware('user');
require_once(__DIR__ . "/web.profile.php");
require_once(__DIR__ . "/web.cms.php");
require_once(__DIR__ . "/web.guest_forms.php");

Route::get('downloads/{filename}', [GuestController::class, 'download'])->name('download');

Route::get('/{slug?}', [GuestController::class, 'show'])->where('slug', '.*');

app/Models/Page.php
<?php

// SPDX-FileCopyrightText: 2021 - 2022 Marten Koetsier <eicas@koetsierengineering.nl>
// SPDX-FileCopyrightText: 2022 Arnout Engelen <arnout@bzzt.net>
//
// SPDX-License-Identifier: MIT

namespace App\Models;

use App\Models\Image;
use App\Models\Imageset;
use App\Models\Pivots\ImagePage;
use App\Models\Redirect;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\MessageBag;
use Str;

class Page extends Model {
	use SoftDeletes;

	public const VISIBILITY = [
		0 => 'review',
		1 => 'public',
	];

	protected $fillable = ['language', 'slug', 'title', 'description', 'template', 'imageset_id', 'visibility'];

	protected $casts = [
		'id' => 'integer',
		'imageset_id' => 'integer',
		'visibility' => 'integer',
		'created_at' => 'datetime',
		'updated_at' => 'datetime',
		'deleted_at' => 'datetime',
	];

	/**
	 * @return string[]
	 */
	public static function getAvailableTemplates() {
		static $templates = null;
		if (is_null($templates)) {
			$templates = [];
			foreach (Storage::disk('templates')->allFiles('') as $filename) {
				if (Str::endsWith($filename, '.blade.php')) {
					$templates[] = str_replace('/', '.', Str::replaceLast('.blade.php', '', $filename));
				}
			}
		}
		return $templates;
	}

	/**
	 * Return a string representation of the visibility.
	 * 
	 * @return string
	 */
	public function getVisibilityLabelAttribute() {
		return self::VISIBILITY[$this->attributes['visibility']] ?? '?';
	}

	public function scopePublic($query) {
		return $query->where('visibility', '>=', 1);
	}

	public function getRelativeUrlAttribute() {
		// perhaps later, the language (ISO-639-1) should also become part of the url.
		return str_replace('//', '/', "/{$this->attributes['slug']}");
	}

	public function scopeRelativeUrl($query, $url) {
		return $query->where('slug', $url);
	}

	public function imagePages() {
		return $this->hasMany(ImagePage::class)->orderBy('order');
	}

	public function images() {
		return $this->belongsToMany(Image::class)
			->using(ImagePage::class)
			->withPivot('id', 'order', 'href', 'alt', 'created_at', 'updated_at')
			->withTimestamps()
			->orderBy('order');
	}

	public function imageset() {
		return $this->belongsTo(Imageset::class);
	}

	public function contents() {
		return $this->hasMany(Content::class)->orderBy('order', 'asc');
	}

	public function trashedContents() {
		return $this->hasMany(Content::class)->onlyTrashed()->orderBy('deleted_at', 'desc');
	}

	protected static function booted() {
		static::updated(function ($page) {
			if ($page->isDirty('slug')) {
				$from = $page->getOriginal('slug');
				$to = $page->slug;
				// logger("dirty slug: '$to' (was: '$from')");
				if (Redirect::checkAll($from, $to)) {
					Redirect::create([
						'from' => $from,
						'to' => $to,
						'comment' => 'automatisch gegenereerd bij aanpassen pagina-url',
					]);
					// logger("redirect created.");
					session()->flash('status', "Er is een redirect gegenereerd voor de oude url: '$from' > '$to'");
				} else {
					$messages = new MessageBag();
					$messages->add(
						'slug',
						'Er is geen redirect gegenereerd voor deze wijziging omdat dat zou leiden tot' .
							' te veel opeenvolgende redirects of omdat er al een redirect bestond voor' .
							' de originele url.'
					);
					session()->flash('errors', $messages);
				}
			}
		});
	}

	/**
	 * Get the url to the current page.
	 *
	 * @return string
	 */
	public function getUrlAttribute(): string {
		return config("app.url") . $this->attributes['slug'];
	}

}

app/Http/Controllers/Cms/CmsController.php
<?php

// SPDX-FileCopyrightText: 2021 Marten Koetsier <eicas@koetsierengineering.nl>
//
// SPDX-License-Identifier: MIT

namespace App\Http\Controllers\Cms;

use App\Http\Controllers\Controller;
use App\Models\Download;
use App\Models\Image;
use App\Models\Imageset;
use App\Models\Page;
use App\Models\Redirect;
use Illuminate\Http\Request;

class CmsController extends Controller {
	public function index() {
		return view('cms.index', [
			'pages_count' => Page::count(),
			'images_count' => Image::count(),
			'imagesets_count' => Imageset::count(),
			'downloads_count' => Download::count(),
			'redirects_count' => Redirect::count(),
			// 'profiles_count' => Profile::count(),
			// 'users_count' => User::count(),
		]);
	}
}

app/Http/Controllers/Cms/DatalimitController.php
<?php

// SPDX-FileCopyrightText: 2022 Marten Koetsier <eicas@koetsierengineering.nl>
//
// SPDX-License-Identifier: MIT

namespace App\Http\Controllers\Cms;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class DatalimitController extends Controller {
	/**
	 * Handle the incoming request.
	 *
	 * @param \Illuminate\Http\Request $request
	 * @return \Illuminate\Http\Response
	 */
	public function __invoke(Request $request) {
		if (!$request->user()->hasRole('admin')) {
			return response('niet toegestaan', 403);
		}
		require base_path('datalimit_config.php');
		$settings = [
			'period' => $period,
			'max_bytes' => $max_bytes,
			'suspend_duration' => $suspend_duration,
		];
		$start_suspends = (new Carbon())->subMonths(6);
		$suspends = DB::connection('datalimit')->select(
			"select `starts_at`, `ends_at`, `comment` from `suspends` where `ends_at` > ? order by `id` desc",
			[$start_suspends->format('Y-m-d H:i:s')]
		);
		$start_visits = (new Carbon())->subDays(14);
		$start_visits->setSecond(0);
		$start_visits->setMinute(15 * (floor($start_visits->minute / 15)));
		$visits = [];
		foreach (DB::connection('datalimit')->select(
			"select" .
			" from_unixtime(900 * floor(unix_timestamp(`visited_at`) / 900)) p," .
			" count(size) n," .
			" sum(size) d" .
			" from visits" .
			" where `visited_at` >= '{$start_visits->format('Y-m-d H:i:s')}'" .
			" group by p" .
			" order by date(`visited_at`) desc, `visited_at`"
		) as $visit) {
			$day = substr($visit->p, 0, 10);
			if (!array_key_exists($day, $visits)) {
				$visits[$day] = [];
			}
			$visits[$day][] = $visit;
		}

		return view('cms.datalimit.index', [
			'settings' => collect($settings),
			'suspends' => collect($suspends),
			'visits' => collect($visits),
		]);
	}
}

app/Http/Controllers/Cms/DownloadController.php
<?php

// SPDX-FileCopyrightText: 2021 Marten Koetsier <eicas@koetsierengineering.nl>
//
// SPDX-License-Identifier: MIT

namespace App\Http\Controllers\Cms;

use App\Http\Controllers\Controller;
use App\Http\Requests\Cms\StoreDownloadRequest;
use App\Http\Requests\Cms\UpdateDownloadRequest;
use App\Models\Download;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class DownloadController extends Controller {
	public function __construct() {
		$this->authorizeResource(Download::class, 'download');
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		return view('cms.downloads.index', ['downloads' => Download::orderBy('created_at', 'desc')->get()]);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param \App\Http\Requests\Cms\StoreDownloadRequest $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(StoreDownloadRequest $request) {
		$download = Download::create([
			'filename' => $request->validated()['file']->getClientOriginalName(),
			'size' => $request->validated()['file']->getSize(),
		]);
		$request->validated()['file']->storeAs(
			'', // root path
			$download->getStoragePathAttribute(), // generate filename, based on timestamp and id
			'downloads' // disk
		);

		return redirect()->route('cms.downloads.index', ['uploaded_id' => $download->id]);
	}

	/**
	 * Display the specified resource.
	 *
	 * @param \App\Models\Download $download
	 * @return \Illuminate\Http\Response
	 */
	public function show(Download $download) {
		return $download->downloadResponse();
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param \App\Http\Requests\Cms\UpdateDownloadRequest $request
	 * @param \App\Models\Download $download
	 * @return \Illuminate\Http\Response
	 */
	public function update(UpdateDownloadRequest $request, Download $download) {
		$download->filename = $request->validated()['filename'];
		$download->save();

		return redirect()->route('cms.downloads.index', ['uploaded_id' => $download->id]);
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param \App\Models\Download $download
	 * @return \Illuminate\Http\Response
	 */
	public function destroy(Download $download) {
		Storage::disk('downloads')->delete($download->getStoragePathAttribute());
		$download->delete();
		return redirect()->route('cms.downloads.index');
	}
}

app/Http/Controllers/Cms/ImageController.php
<?php

// SPDX-FileCopyrightText: 2021 Marten Koetsier <eicas@koetsierengineering.nl>
//
// SPDX-License-Identifier: MIT

namespace App\Http\Controllers\Cms;

use App\Http\Controllers\Controller;
use App\Http\Requests\Cms\DeleteImageRequest;
use App\Http\Requests\Cms\StoreImageRequest;
use App\Http\Requests\Cms\UpdateImageRequest;
use App\Models\Image;
use Illuminate\Http\Request;

class ImageController extends Controller {
	public function __construct() {
		$this->authorizeResource(Image::class, 'image');
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		$images = Image::with(['large', 'small'])->orderBy('created_at', 'desc')->get();

		return view('cms.images.index', ['images' => $images]);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		return view('cms.images.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param \App\Http\Requests\Cms\StoreImageRequest $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(StoreImageRequest $request) {
		$image = Image::storeFile($request->validated()['image'], $request->validated()['alt']);

		if (!$image) {
			return redirect()->back()->withErrors(['image' => 'Fout bij het opslaan van het bestand.']);
		}

		$request->session()->flash('updated_id', $image->id);
		return redirect()->route('cms.images.index');
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param \App\Models\Image $image
	 * @return \Illuminate\Http\Response
	 */
	public function edit(Image $image) {
		return view('cms.images.edit', ['image' => $image]);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param \App\Http\Requests\Cms\UpdateImageRequest $request
	 * @param \App\Models\Image $image
	 * @return \Illuminate\Http\Response
	 */
	public function update(UpdateImageRequest $request, Image $image) {
		$validated = $request->validated();
		if (isset($validated['image_id']) && !$validated['image_id']) {
			$validated['image_id'] = null;
		}
		$image->fill($validated);
		$image->save();
		$request->session()->flash('status', "Omschrijving opgeslagen.");
		$request->session()->flash('updated_id', $image->id);
		return redirect()->route('cms.images.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param \App\Http\Requests\Cms\DeleteImageRequest $request
	 * @param \App\Models\Image $image
	 * @return \Illuminate\Http\Response
	 */
	public function destroy(DeleteImageRequest $request, Image $image) {
		$image->delete();
		return redirect()->route('cms.images.index');
	}
}

app/Http/Controllers/Cms/ImagePickerController.php
<?php

// SPDX-FileCopyrightText: 2021 Marten Koetsier <eicas@koetsierengineering.nl>
//
// SPDX-License-Identifier: MIT

namespace App\Http\Controllers\Cms;

use App\Http\Controllers\Controller;
use App\Models\Image;
use Illuminate\Http\Request;

class ImagePickerController extends Controller {
	/**
	 * Display a listing of the resource.
	 *
	 * @param \Illuminate\Http\Request $request
	 * @return \Illuminate\Http\Response
	 */
	public function index(Request $request) {
		$data = $request->validate([
			'image_picker_id' => 'required|string|UUID',
		]);
		$images = Image::get();

		return view('components.image-picker.index', [
			'images' => $images,
			'image_picker_id' => $data['image_picker_id'],
		]);
	}
}

app/Http/Controllers/Cms/ImagesetController.php
<?php

// SPDX-FileCopyrightText: 2021 Marten Koetsier <eicas@koetsierengineering.nl>
//
// SPDX-License-Identifier: MIT

namespace App\Http\Controllers\Cms;

use App\Http\Controllers\Controller;
use App\Http\Requests\Cms\StoreImagesetRequest;
use App\Http\Requests\Cms\UpdateImagesetRequest;
use App\Models\Imageset;
use Illuminate\Http\Request;

class ImagesetController extends Controller {
	public function __construct() {
		$this->authorizeResource(Imageset::class, 'imageset');
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		$imagesets = Imageset::withCount(['images', 'pages'])->get();

		return view('cms.imagesets.index', ['imagesets' => $imagesets]);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param \App\Http\Requests\Cms\StoreImagesetRequest $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(StoreImagesetRequest $request) {
		$imageset = Imageset::create($request->validated());
		return redirect()->route('cms.imagesets.index', ['updated_id' => $imageset->id]);
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param \App\Models\Imageset $imageset
	 * @return \Illuminate\Http\Response
	 */
	public function edit(Imageset $imageset) {
		$imageset->load('images')->loadCount('pages');
		return view('cms.imagesets.edit', ['imageset' => $imageset]);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param \App\Http\Requests\Cms\UpdateImagesetRequest $request
	 * @param \App\Models\Imageset $imageset
	 * @return \Illuminate\Http\Response
	 */
	public function update(UpdateImagesetRequest $request, Imageset $imageset) {
		$imageset->fill($request->validated());
		$imageset->save();
		return redirect()->route('cms.imagesets.index', ['updated_id' => $imageset->id]);
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param \App\Models\Imageset $imageset
	 * @return \Illuminate\Http\Response
	 */
	public function destroy(Imageset $imageset) {
		$imageset->delete();
		return redirect()->route('cms.imagesets.index');
	}
}

app/Http/Controllers/Cms/Imagesets/SwapImageImagesetController.php
<?php

// SPDX-FileCopyrightText: 2021 Marten Koetsier <eicas@koetsierengineering.nl>
//
// SPDX-License-Identifier: MIT

namespace App\Http\Controllers\Cms\Imagesets;

use App\Http\Controllers\Controller;
use App\Models\Imageset;
use App\Models\Pivots\ImageImageset;

class SwapImageImagesetController extends Controller {
	/**
	 * Swap the given imageImagesets (for the given Imageset).
	 *
	 * Note that the ImageImageset is a pivot model which doesn't load properly from the service container. Therefore,
	 * it is inserted as integer and resolved in this function.
	 * 
	 * @param \App\Models\Imageset $imageset
	 * @param integer $imageImageset1
	 * @param integer $imageImageset2
	 * @return \Illuminate\Http\Response
	 */
	public function __invoke(Imageset $imageset, int $imageImageset1, int $imageImageset2) {
		$imageImageset1 = ImageImageset::where('imageset_id', $imageset->id)->findOrFail($imageImageset1);
		$imageImageset2 = ImageImageset::where('imageset_id', $imageset->id)->findOrFail($imageImageset2);

		$tmp_order = $imageImageset1->order;
		$imageImageset1->order = $imageImageset2->order;
		$imageImageset2->order = $tmp_order;
		$imageImageset1->save();
		$imageImageset2->save();

		return redirect()->route('cms.imagesets.edit', ['imageset' => $imageset]);
	}
}

app/Http/Controllers/Cms/MultiImagePickerController.php
<?php

// SPDX-FileCopyrightText: 2021 Marten Koetsier <eicas@koetsierengineering.nl>
//
// SPDX-License-Identifier: MIT

namespace App\Http\Controllers\Cms;

use App\Helpers\Misc;
use App\Http\Controllers\Controller;
use App\Models\Image;
use Illuminate\Http\Request;

class MultiImagePickerController extends Controller {
	/**
	 * Display a listing of the resource.
	 *
	 * @param \Illuminate\Http\Request $request
	 * @return \Illuminate\Http\Response
	 */
	public function index(Request $request) {
		$data = $request->validate([
			'multi_image_picker_id' => 'required|string',
			'selected_image_ids' => 'nullable|string|regex:/[0-9,]*/',
		]);
		$images = Image::get();
		$selected_image_ids = Misc::commaSeparatedToIntegerArray($data['selected_image_ids'] ?? '');

		return view('components.multi-image-picker.index', [
			'images' => $images,
			'multi_image_picker_id' => $data['multi_image_picker_id'],
			'selected_image_ids' => $selected_image_ids,
		]);
	}
}

resources/views/cms/pages/edit.blade.php
{{--
SPDX-FileCopyrightText: 2021 Marten Koetsier <eicas@koetsierengineering.nl>
SPDX-FileCopyrightText: 2022 Arnout Engelen <arnout@bzzt.net>

SPDX-License-Identifier: MIT
--}}

@extends('layouts.user')

@section('main')
	<form id="edit" method="POST" action="{{ route('cms.pages.update', ['page' => $page]) }}">
		@csrf
		@method('PATCH')

		<h2>Pagina wijzigen</h2>

		<input type="hidden" name="language" value="{{$page->language}}">

		<label>Url</label>
		<input type="text" name="slug" value="{{ old('slug', $page->slug) }}" required>

		<label>Titel</label>
		<input type="text" name="title" value="{{ old('title', $page->title) }}">

		<label>Omschrijving</label>
		<input type="text" name="description" value="{{ old('description', $page->description) }}">

		<label>Template</label>
		<select name="template">
			@foreach (App\Models\Page::getAvailableTemplates() as $template)
			<option value="{{ $template }}"{!!
				$template === $page->template ? ' selected' : ''
			!!}>{{ $template }}</option>
			@endforeach
		</select>

		<label>Beeld-lijst</label>
		<select name="imageset_id">
			<option value=""{!! !$page->imageset_id ? ' selected' : '' !!}>-</option>
			@foreach ($imagesets as $imageset)
			<option value="{{ $imageset->id }}"{!!
				$page->imageset_id === $imageset->id ? ' selected' : ''
			!!}>{{ $imageset->name }} ({{ $imageset->images_count }} beelden)</option>
			@endforeach
		</select>

		<label>Zichtbaarheid</label>
		<select name="visibility">
			@foreach (App\Models\Page::VISIBILITY as $index => $label)
			<option value="{{ $index }}"{!!
				$index === $page->visibility ? ' selected' : ''
			!!}>{{ $label }}</option>
			@endforeach
		</select>

		<button type="submit">opslaan</button>
	</form>
	<hr>
	<p><a class="button" href="{{ route('cms.pages.contents.index', ['page' => $page])}}">Pagina-inhoud aanpassen</a></p>
@endsection

resources/views/cms/pages/index.blade.php
{{--
SPDX-FileCopyrightText: 2021 Marten Koetsier <eicas@koetsierengineering.nl>
SPDX-FileCopyrightText: 2022 Arnout Engelen <arnout@bzzt.net>

SPDX-License-Identifier: MIT
--}}

@extends('layouts.user')

@section('main')
	<h2>Pagina's</h2>
	<form class="no-layout" id="create" method="POST" action="{{ route('cms.pages.store') }}">
		@csrf
		<input form="create" type="hidden" name="language" value="{{ config('app.locale') }}">
		<input form="create" type="hidden" name="visibility" value="0">
	</form>

	<table>
		<thead>
			<tr>
				<th>Url</th>
				<th>Titel</th>
				<th>Template</th>
				<th>Beeld-lijst</th>
				<th>Zichtbaar</th>
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody>
			@php
				$updated_id = session()->get('updated_id', 0);
			@endphp
			@foreach ($pages as $page)
			<tr{!! $page->id === $updated_id ? ' class="updated"' : '' !!}>
				<td>{{ $page->relative_url }}</td>
				<td>{{ $page->title }}</td>
				<td>{{ $page->template }}</td>
				<td>{{ $page->imageset ? $page->imageset->name : '-' }}</td>
				<td>{{ $page->visibility_label }}</td>
				<td>
					<div>
						<a class="button" href="{{ route('cms.pages.edit', ['page' => $page]) }}">Bewerken</a>
						<form class="no-layout" id="delete_{{ $page->id }}" method="POST" action="{{
							route('cms.pages.destroy', ['page' => $page])
						}}" onsubmit="return confirm('Zeker weten? Actie is definitief!');">
							@csrf
							@method('DELETE')
							<button type="submit">Verwijderen</button>
						</form>
					</div>
				</td>
			</tr>
			@endforeach
			<tr><th colspan="6">Nieuwe pagina</th></tr>
			<tr>
				<td><input form="create" type="text" name="slug" value="{{ old('slug') }}"></td>
				<td><input form="create" type="text" name="title" value="{{ old('title') }}" required></td>
				<td>
					<select form="create" name="template">
						@foreach (App\Models\Page::getAvailableTemplates() as $template)
						<option value="{{ $template }}"{!!
							$template === 'story' ? ' selected' : ''
						!!}>{{ $template }}</option>
						@endforeach
					</select>
				</td>
				<td>
					<select form="create" name="imageset_id">
						<option value="" selected>-</option>
						@foreach ($imagesets as $imageset)
						<option value="{{ $imageset->id }}">{{ $imageset->name }}</option>
						@endforeach
					</select>
				</td>
				<td>
					Omschrijving:
				</td>
				<td>
					<input form="create" type="text" name="description" value="{{ old('description') }}">
				</td>
			</tr>
			<tr>
				<td colspan="5"></td>
				<td><button form="create" type="submit">Opslaan</button></td>
			</tr>
		</tbody>
	</table>
@endsection